"""Add polygon points to Report model

Revision ID: 4226e0eb1d2d
Revises: 76358b2dcdf0
Create Date: 2025-02-13 09:45:38.156334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4226e0eb1d2d'
down_revision = '76358b2dcdf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('polygon_points', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('polygon_points')

    # ### end Alembic commands ###
